export {
  WORKER_CHAT_CLEAR_HEADING,
  WORKER_CHAT_DISCLAIMER,
  WORKER_CHAT_SHEET_COPY,
  WORKER_CHAT_WHAT_NOW_HEADING,
  buildWorkerStarterQuestions,
  ensureWorkerChatDisclaimer,
  extractWorkerChatSections,
  extractWorkerClearAnswer,
  extractWorkerWhatToDoNow,
  formatWorkerChatAnswer,
  hasForbiddenLiveValidationClaim,
  hasForbiddenWorkerBrand,
  hasForbiddenWorkerChatClaim,
  hasInventedLegalCitation,
  sanitizeWorkerChatCopy,
  stripInventedLegalCitations,
  stripLiveValidationClaims,
} from "@shared/workerChatUx";
